### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by nsane9129** [enveda/kgem-ensembles-in-drug-discovery#1]
I tried to run the get_predictions file but  I m getting this error :

![dd](https://user-images.githubusercontent.com/31731547/212773798-d7eff381-a197-4127-aef3-db744c7eae0e.JPG)
![cc](https://user-images.githubusercontent.com/31731547/212773864-4e488e25-643e-4475-a40e-ade144e5791f.JPG)

**Comment by ddomingof** [comment]
Hi @nsane9129 ,
You havent downloaded the data (https://zenodo.org/record/7002695). That data (zip) has to be exported under the main directory of the repository and there should be a file called `./data/kg/train.tsv`, as stated in the error.
