### ISSUE TITLE
INFO:__main__:Merging predictions from predictions' csv's.

### ISSUE THREAD

**Issue by nsane9129** [enveda/kgem-ensembles-in-drug-discovery#3]
![1](https://user-images.githubusercontent.com/31731547/213860491-e6d1b921-e652-45a4-a46a-c3cdec675fbc.JPG)
![2](https://user-images.githubusercontent.com/31731547/213860492-e9fd12f8-7520-4887-bd85-158bcc36dfa2.JPG)
![3](https://user-images.githubusercontent.com/31731547/213860493-e762ee17-d50f-491f-a1ac-73d3f13b5637.JPG)
![4](https://user-images.githubusercontent.com/31731547/213860495-a6250420-c8e3-45e5-8776-8fb7b8deec97.JPG)
![5](https://user-images.githubusercontent.com/31731547/213860497-60f804d4-0107-4ab5-8fba-ecbc22dca75b.JPG)
![6](https://user-images.githubusercontent.com/31731547/213860498-d6d4c850-f08d-4c39-bd6e-c5d75ade7daf.JPG)

**Comment by ddomingof** [comment]
Hi @nsane9129,
Have you loaded the predictions we provided? or how are you generating this error?
The error says that the column `tail_id` doesnt exist. Can you please check which columns have you loaded in your dataframe. Without more context it is impossible for us to help you.

Regards

**Comment by nsane9129** [comment]
Hello @ddomingof , 
Thank you for your reply.
I want to generate my own predictions?
What should I do ?

**Comment by ddomingof** [comment]
First, you have to train KGEMs on your own KG.
To do so, you have to use this script (https://github.com/enveda/kgem-ensembles-in-drug-discovery/blob/main/src/train_model.py) or PyKEEN with your own splits.
Then, we you have to reproduce the code in the notebooks, being aware of the columns matching, or changing them on the notebooks. You can download the dataset we provide with the results and see which columns are needed but it is the same format that PyKEEN provides

**Comment by nsane9129** [comment]
Thank you for your help @ddomingof. I reproduced the code as you told me to do. However, due the fact I have a limited memory I had I guess I had a RUNTIMEWarning error (overeaflow encountred in long_scalars)
So,I tried to reproduce it on colab . Do you think that it will work this way?

**Comment by ddomingof** [comment]
Hard to say, how large are the models in GBs? you need a ram at least that big
