### ISSUE TITLE
 main function in full_pipeline.py

### ISSUE THREAD

**Issue by Zhaodouad** [enveda/kgem-ensembles-in-drug-discovery#5]
Hello, may I ask what is commented out in the main function in full_pipeline.py? Do I need to run this?
<img width="1279" alt="1703255216238" src="https://github.com/enveda/kgem-ensembles-in-drug-discovery/assets/111046917/641a2738-cd64-4901-8ba5-72b539875b8f">
<img width="1280" alt="1703255186808" src="https://github.com/enveda/kgem-ensembles-in-drug-discovery/assets/111046917/3981d93d-042f-487a-b570-e70b51cfc050">

**Comment by YojanaGadiya** [comment]
@Zhaodouad these are just plotting functions that were used for the manuscript hence commented.

**Comment by Zhaodouad** [comment]
Hi there! Thank you so much for taking the time to reply. Thank you again for your help!
Your articles have helped me a lot in learning the pykeen library. I have a question though - I've been trying to retrain transE and other models using the openbiolink dataset (the model parameters are JSON files in the kgem-params directory), but I've noticed that my training results are quite different from the values in the model files provided by your team. In fact, my training results are lower than expected. Do you have any suggestions or tips to improve my results?

At 2024-01-02 17:50:44, "Yojana Gadiya" ***@***.***> wrote:

@Zhaodouad these are just plotting functions that were used for the manuscript hence commented.
