### ISSUE TITLE
retrain the model

### ISSUE THREAD

**Issue by Zhaodouad** [enveda/kgem-ensembles-in-drug-discovery#6]
I want to retrain the model, but the training effect is very poor, the training parameter is the.json file in the kgem-params folder, what should I do to retrain the model?

**Comment by ddomingof** [comment]
What do you mean with 'but the training effect is very poor' ?

To retrain the model you have to run [this script](https://github.com/enveda/kgem-ensembles-in-drug-discovery/blob/main/src/train_model.py)
